### ISSUE TITLE
Filtering partials with watch in Gulp

### ISSUE THREAD

**Issue by timkelty** [carlosl/gulp-nunjucks-render#24]
In my `views` folder, I have a folders that start with  `_` that contain partials, that I'm filtering out from rendering:

```
var views = path.join(config.paths.src, 'views');
var src = [
  path.join(views, '**/*.html'),
  '!' + path.join(views, '_*/*'),
];
nunjucksRender.nunjucks.configure(
  [views],
  { watch: false }
);

gulp.task('build:html:render', function() {
  return gulp.src(src)
  .pipe(nunjucksRender())
  .pipe(gulp.dest(dest));
});

```

This works great with one exception: When I run this task from `gulp.watch`, it only runs when I save one of my non-underscored files, but I want it to re-render everything on any save with `views`.

```
  gulp.watch([
    path.join(config.paths.src, 'views/**/*.html'),
  ], gulp.series(
    'build:html:render'
  ));
```

Any ideas?

**Comment by kamlekar** [comment]
I am actually doing something like this to exclude "_" files. I hope it will be helpful for you:

	var gulp = require('gulp');
	var nunjucksRender = require('gulp-nunjucks-render');

	gulp.task('default', function () {
	    nunjucksRender.nunjucks.configure(['html/']);
	    return gulp.src('templates/!(_)*.html')
	        .pipe(nunjucksRender())
	        .pipe(gulp.dest('dist'));
	});
	gulp.task('watch', function () {
	    gulp.watch(['templates/*.html'], ['default']);
	});

**Comment by timkelty** [comment]
Yeah, that's essentially the same thing I'm doing. Both work fine when just compiling. The problem is when watching, the templates aren't re-built when you save one of the `_` files, since it is filtered out of the stream.

**Comment by kamlekar** [comment]
I don't think the above code which I provided is not watching the files with `_` prefix. The code I provided is actually watching all the files but compiling only the files which aren't prefixed with `_`.

**Comment by carlosl** [comment]
@kamlekar is correct, his watch ```gulp.watch(['templates/*.html'], ['default']);``` is watching all html files in the template directory, might want to add ```**/*.html``` if you have the "_" files in sub-directories though.

**Comment by carlosl** [comment]
Please close or let me know if your issue has been solved.

**Comment by timkelty** [comment]
will do - testing now

**Comment by timkelty** [comment]
Figured it out! I wasn't related to underscored directories at all.

I was doing `nunjucksRender.nunjucks.configure` _outside_ of the `gulp.task` callback. As soon as I put it inside, everything works!

My bad, thanks for stickin' with me!

**Comment by carlosl** [comment]
Awesome. Closing this out.

**Comment by ReloadInteractive** [comment]
Hi Timkelty and kamlekar, any chance you could show me how you achieved this in the end, I need to exclude the includes folder too :)

**Comment by timkelty** [comment]
@ReloadInteractive, I have:
```
  var nunjucksRender = require('gulp-nunjucks-render');
  var views = path.join(process.cwd(), 'views');
  var src = [
    path.join(views, '**/*.{nunj,nunjucks}'),
    '!' + path.join(views, '_*/*'),
  ];

  gulp.task('build:html', function() {
    nunjucksRender.nunjucks.configure(
      [views],
      { watch: false }
    );

    return gulp.src(src)
    .pipe(nunjucksRender())
    .pipe(gulp.dest(dest));
  });
```

The only confusion for me was it was important to have the `nunjucksRender.nunjucks.configure` _inside_ the `gulp.task` callback, not outside.
