### ISSUE TITLE
Maintaned?

### ISSUE THREAD

**Issue by kristijanhusak** [carlosl/gulp-nunjucks-render#25]
Is this plugin maintained?

**Comment by kamlekar** [comment]
To author, please give update on this.

**Comment by carlosl** [comment]
Hey, sorry for the delay. I have not been able to keep up on the maintenance of this project, it seems to work as I have used it in various projects recently without modifying anything but haven't had the time to focus on specific bugs or adding new features.

I do see some code commits that I will tend to later today, but I have no problem if anybody would like to pick this up and continue to maintain it as I have been mostly focused on my family and super busy with work lately.

**Comment by kamlekar** [comment]
I surely can't maintain it as I am not aware of the background stuff. I will try to understand it this weekend and try to help you. TBH, I really like the idea of rendering files in local itself.

**Comment by kristijanhusak** [comment]
I found several bugs:

* when you run task for this as a single action (without watcher), it just stays, never finishes. For example `gulp nunjucks`, where `nunjucks` is the task that does compiling. Maybe just for me, please test from your side if possible.

* When syntax error occurs, it crashes the watcher. Code misses try/catch block around compiling error.

I can fix 2nd issue, but i'm still not sure about the first one. I will create PR next week.

**Comment by kamlekar** [comment]
I am not sure, maybe the first error can be fixed by adding `{ watch: false }` as shown in this code:

    gulp.task('default', function () {
        nunjucksRender.nunjucks.configure(['templates/'], { watch: false });
        return gulp.src('templates/!(_)*.html')
            .pipe(nunjucksRender({ }))
            .pipe(gulp.dest('site'));
    });

**Comment by kristijanhusak** [comment]
@kamlekar 
Yes, that fixes the first issue. Thanks!

Still needs the fix for 2nd one. I'll create PR.

@carlosl I can take over the maintaining of this. Can you give me access or transfer it to me?

**Comment by kamlekar** [comment]
I think someone should mention the first issue fix in Readme.

**Comment by kristijanhusak** [comment]
@kamlekar 
`watch: false` is already on the master branch in code, but still not in stable release.

**Comment by carlosl** [comment]
@kristijanhusak , I'm currently pulling in some merges but I really appreciate the help. I will give you access.

**Comment by carlosl** [comment]
@kristijanhusak I gave you access and have updated the readme.

**Comment by kristijanhusak** [comment]
@carlosl Thanks! I was out of town last few days, so I wasn't able to handle things around.

**Comment by kristijanhusak** [comment]
@carlosl I hope you will get to this notification, but can you please add me as a collaborator on npmjs? Here's the profile: https://www.npmjs.com/~kristijanhusak 
If you do not answer I will create a fork and continue maintaining there.

**Comment by kamlekar** [comment]
:+1: but do wait till a reasonable time. Also notify the watchers.

**Comment by kristijanhusak** [comment]
I got full access, so everything is up to date now.

**Comment by TheDancingCode** [comment]
@kristijanhusak 
Almost all open issues have been answered and can be closed. Would be good to do so.

**Comment by kristijanhusak** [comment]
@TheDancingCode I closed some issues and merged in your PR. I would gladly add you as collaborator, but only @carlosl can do that.

**Comment by TheDancingCode** [comment]
Alright, great. Looks much less cluttered now.
