### ISSUE TITLE
Templating relative path

### ISSUE THREAD

**Issue by sumerokr** [carlosl/gulp-nunjucks-render#3]
Is it possible to set path to `{% extends parent.html %}` via path relative to child.html?
Currently it's relative to project root.

E.g. something like this
`{% extends layout/parent.html %}`
and not
`{% ./app/views/layout/parent.html %}`

**Comment by jlongster** [comment]
Relative paths works now: https://github.com/mozilla/nunjucks/releases/tag/v1.3.0
