### ISSUE TITLE
Update npm release

### ISSUE THREAD

**Issue by fongandrew** [carlosl/gulp-nunjucks-render#32]
NPM repo appears to be four months behind and does not include some of the latest commits. Can someone with access please update the version number and release?

https://www.npmjs.com/package/gulp-nunjucks-render

**Comment by DaBs** [comment]
Seconded. I'm currently using my own local branch of this package in a production environment, which should NEVER be happening, but is a necessity because of the lack of updates to the NPM repo.

**Comment by DaBs** [comment]
@carlosl I understand you are the only one with access to the npm repo. Can this be fixed?

**Comment by carlosl** [comment]
Sorry for the delay, this was pushed to NPM just now.
