### ISSUE TITLE
Add Custom Filters

### ISSUE THREAD

**Issue by jtini** [carlosl/gulp-nunjucks-render#36]
Hi @carlosl,

Do you have any examples of a custom filters working with your module? I have been trying without much luck. It seems to be something around the nunjucks environment and getting it setup properly with your module. Love some help with the below.

```javascript
var render       = require('gulp-nunjucks-render')
var env          = new render.nunjucks.Environment()

env.addFilter('log', function(str){
  console.log(str);
  return str;
});

var htmlTask = function() {
  render.nunjucks.configure([path.join(config.root.src, config.tasks.html.src)], { watch: false })

  return gulp.src(paths.src)
    .pipe(data(getData))
    .on('error', handleErrors)
    .pipe(render(null, null, env))
    .on('error', handleErrors)
    .pipe(gulpif(process.env.NODE_ENV == 'production', htmlmin(config.tasks.html.htmlmin)))
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream())
}

gulp.task('html', htmlTask)

```

Thanks!

**Comment by kristijanhusak** [comment]
hi @jtini,

What exactly you want to do with the filters? Do you mean custom filters in nunjucks, or some gulp task stream filtering?

**Comment by corbanb** [comment]
@kristijanhusak I was working with @jtini on this also. the main goal is to add a custom nunjucks filter. 

See: https://mozilla.github.io/nunjucks/api#custom-filters

I believe we should be able to do the able but I am a little unclear on if the new environment is being used for your module when we create it. Thoughts?

Thanks for getting back.

**Comment by kristijanhusak** [comment]
@corbanb That is not possible at this moment. I have plan for rewriting and adding that functionality, but I am not able to update npm repository until @carlosl gives me access. Will let you know when i manage to set up something.

**Comment by corbanb** [comment]
sooo what do we gotta do here @carlosl ? :moneybag: ? :hand: ? :facepunch: ? :)

**Comment by kristijanhusak** [comment]
@corbanb @jtini I done some refactoring on the fork. It's still not published to npm, but you could give it a try. I added an option to manipulate the environment, and also did some refactoring on path setup. Check the readme and let me know how it works for u.

**Comment by kamlekar** [comment]
Seems like we have no other option. I hope @carlosl will respond soon. Anyway :+1:

**Comment by carlosl** [comment]
Sorry guys... Feel your pain, @kristijanhusak giving you access to NPM now.

**Comment by corbanb** [comment]
@kristijanhusak and @carlosl thanks guys. I did the same thing on my end by forking. I like your implementation better and will test soon. Thanks!

**Comment by kristijanhusak** [comment]
thanks @carlosl . I'll merge new code from my fork and publish it as 2.0.0, because it has breaking changes.

**Comment by kamlekar** [comment]
:+1:

**Comment by kristijanhusak** [comment]
@kamlekar @corbanb I updated it to version 2.0.0. Check the readme and changelog how to update.

**Comment by carlosl** [comment]
Thanks @kristijanhusak !
