### ISSUE TITLE
How to manage tags configuration?

### ISSUE THREAD

**Issue by fstn** [carlosl/gulp-nunjucks-render#40]
I try to change default tags:
gulp.task('default', function () {
  return gulp.src('src/templates/*.html')
    .pipe(nunjucksRender({
         tags: {
    blockStart: '<%',
    blockEnd: '%>',
    variableStart: '<$',
    variableEnd: '$>',
    commentStart: '<#',
    commentEnd: '#>'
  },
      path: ['src/templates/'] // String or Array
    }))
    .pipe(gulp.dest('dist'));
});

it doesn't work

thanks

**Comment by carlosl** [comment]
Hey, you can set this in the config stage...

```
nunjucksRender.nunjucks.configure('src/templates/', {
  tags: {
    blockStart: '<%',
    blockEnd: '%>',
    variableStart: '<$',
    variableEnd: '$>',
    commentStart: '<#',
    commentEnd: '#>'
  }
});

gulp.task('default', function () { 
  // all the same gulp stuff you have minus the tags
 });

```
