### ISSUE TITLE
Template not found.

### ISSUE THREAD

**Issue by dutraveller** [carlosl/gulp-nunjucks-render#44]
Hello,
I've adding some errors that i don't understand, because the path is right.

Template render error in plugin 'gulp-nunjucks'
(unknown path)
  Error: template not found: layout.njk
gulp file:

```
nunjucksRender.nunjucks.configure(['_src/templates/']);

// Gets .html and .nunjucks files in pages
return gulp.src('_src/pages/**/*.+(html|nunjucks|njk)')
```

And the files are there:

_src
--templates
---layout.njk

Thank you

**Comment by thiagodebastos** [comment]
@dutraveller The same thing happened to me when I updated gulp-nunjucks-render from 1.1.10 to 2.0.0. I haven't used nunjucks in a while, perhaps a few things have changed in the config settings? I will look into it and let you know if I figure it out.
