### ISSUE TITLE
Small Changes Not Compiled

### ISSUE THREAD

**Issue by 58bits** [carlosl/gulp-nunjucks-render#46]
Have a weird problem with nunjucks. When I make small changes to a comment section in a parent template, the 'page' template that extends the parent, does not get compiled (although the file to be compiled _is_ being passed to nunjucks). If I type an extra word or two in the source parent template, all works as expected. I suspect this is a nunjucks problem, and not gulp-nunjucks-render - but thought I'd post here as well just in case I'm missing something obvious.

Here's the issue I've posted with nunjucks... https://github.com/mozilla/nunjucks/issues/810

**Comment by kamlekar** [comment]
That possibly happens because of cache. Try clearing cache or commenting
sourcemaps code.

**Comment by 58bits** [comment]
Hi @kamlekar - thanks for the reply. Can I ask - what cache? This is a server-side render, and the templates/files are being rendered by `compile.renderString` - before being placed in the stream/buffer queue for Gulp to write to dis via `gulp.dest('./public')`

**Comment by 58bits** [comment]
Ignore me - found the problem. The IDE was not writing the changes to disk (although they were being shown in the editor window).
