### ISSUE TITLE
how to disable auto escaping?

### ISSUE THREAD

**Issue by cesarvarela** [carlosl/gulp-nunjucks-render#49]
tried

```
  .pipe($.nunjucksRender({
      path: 'app',
      autoescape: false
  }))
```

but didn't work

**Comment by dkbnguyen** [comment]
I don't think this `autoescape` seems to work
```
.pipe(nunjucksRender({	
    path:'src/templates'
    envOptions: {autoescape: false},
}))
```
This is closer to readme instruction but still doesn't work.

Hope there is a reply on this.

**Comment by sebudde** [comment]
`envOptions: {autoescape: false}` works for me. Thanks!

**Comment by revelt** [comment]
As @sebudde mentioned, the `autoescape` has to be set customising the environment options, not passing in the options object. This issue can be closed.
