### ISSUE TITLE
Can path have multiple sources?

### ISSUE THREAD

**Issue by jitendravyas** [carlosl/gulp-nunjucks-render#50]
I want to keep page specific partial in page directory 

Instead
`path: 'src/templates'`
this
`path: 'src/templates', 'src/pages/**/partials'`

is it possible? I tried that way but it's not working.

**Comment by kamlekar** [comment]
Try to pass as array.

    ['src/templates', 'src/pages/**/partials']

**Comment by jitendravyas** [comment]
I tried it but it's not working

```
  .pipe(nunjucksRender({
      path: ['src/templates', 'src/pages/**/**/includes']
    }))
```

error
`Error: template not found: component1.nunjucks`

**Comment by kamlekar** [comment]
I think you meant like this:

    .pipe(nunjucksRender({
          path: ['src/templates/**/*.nunjucks', 'src/pages/**/*.nunjucks']
    }))

**Comment by jitendravyas** [comment]
Array not working is a different problem but even after replacing this `path: ['src/templates']` with this path: ['src/templates/**/*.nunjucks'] has started giving error

**Comment by jitendravyas** [comment]
This is also not working 
` path: ['src/templates', 'src/partials']`

**Comment by zellwk** [comment]
@jitendravyas `['src/templates'] with this path: ['src/templates/*/.nunjucks']` means you're looking for ONE file named `.nunjucks`. I believe you meant what @kamlekar mentioned. You might want to read up on globbing / put up a github repo so we can know what you're after. It's hard to debug without a seeing the file structure

**Comment by kamlekar** [comment]
@zellwk  I think @jitendravyas  already got the answer on SO. @jitendravyas please close this issue, if you already got the solution.
