### ISSUE TITLE
Update for nunjucks 3.0.0

### ISSUE THREAD

**Issue by Minecrell** [carlosl/gulp-nunjucks-render#54]
[nunjucks 3.0.0](https://github.com/mozilla/nunjucks/releases/tag/v3.0.0) was released, any chance you can update this plugin to make it use the new version? Thanks!

**Comment by Minecrell** [comment]
I'm closing this since @mohitsinghs https://github.com/mohitsinghs/gulp-nunjucks-md can be used for an updated version of `gulp-nunjucks-render`. It works fine for rendering regular HTML pages.

**Comment by kamlekar** [comment]
Why this isn't being updated?

**Comment by Minecrell** [comment]
@kamlekar I don't know, it seems like @carlosl is no longer maintaining it.

**Comment by mohitsinghs** [comment]
@Minecrell @carlosl is back and I tried explaining the differences between this plugin and my plugin in with [an example](https://github.com/mohitsinghs/gulp-nunjucks-md/blob/master/readme.md).

**Comment by Minecrell** [comment]
@mohitsinghs Oh, in this case I'll reopen this issue. Since you have updated nunjucks in your plugin and the old, regular HTML page rendering is still working, is there anything that would speak against merging your changes into `gulp-nunjucks-render`?

**Comment by mohitsinghs** [comment]
@Minecrell 
>is there anything that would speak against merging your changes into `gulp-nunjucks-render` ?

Yes, The way I used markdown and front-matter. I don't think everyone will prefer my way, so why not have two options. Anyway everything which works with this plugin should work fine.
I just don't wanted to add two or more extra plugins ( gulp-data and gulp-front-matter ) and a hacky function to achieve what I wanted and hence I created that plugin. You can consider my plugin as some cool extras functions added to this plugin which should be avoided for simple uses. You can see #55 for what I wanted. I hope you got your answer. Thanks.

**Comment by kevinmpowell** [comment]
I've added a PR to update to nunjucks 3.0.0

https://github.com/carlosl/gulp-nunjucks-render/pull/58

**Comment by kamlekar** [comment]
@kristijanhusak Can you please add @revelt to list of maintainers? I think he is interested to be part. Thanks.
