### ISSUE TITLE
variables bleed between templates...

### ISSUE THREAD

**Issue by maranomynet** [carlosl/gulp-nunjucks-render#6]
I'm using a fairly straightforward gulp task to render all files in a folder.

```js
nunjucksRender.nunjucks.configure(['src/tmpl/']);
return gulp.src('src/tmpl/*.htm')
    .pipe( plumber() )
    .pipe( nunjucksRender() )
    .pipe( gulp.dest( 'site/' ) );
```

But what I'm seeing is that variables (and macros) defined/set in one template are accessible in another...

If my `src/tmpl/` folder contains two files:

```
src/tmpl/
        page1.htm
        page2.htm
```

and `src/tmpl/page1.htm` contains:

```html
{% set customAttr = "class='foobar'" %}
<p {{customAttr}}>Hello World</p>
```

and `src/tmpl/page2.htm` contains:

```html
<p {{customAttr}}>Bonjour!</p>
```

then the rendered output for `site/page2.html` becomes this:

```html
<p class='foobar'>Bonjour!</p>
```

which makes life very difficult when one has lots of templates.

**Comment by maranomynet** [comment]
Any news?

**Comment by nenadjelovac** [comment]
@carlosl any progress on this?

**Comment by silvenon** [comment]
It shouldn't be such a problem, just reset the variable on each page. @nenadjelovac do you have a situation where this behavior is extremely inconvenient?

**Comment by maranomynet** [comment]
This is indeed **very** inconvenient for any project with more than a handful of variables and pages.

Each time you want to add a new variable, you're forced to manually add it to every single page.

Changing a variable's default value also requires going through every page and selectively update the variable.

**Comment by silvenon** [comment]
Yeah, I understand, I wasn't thinking big. Maybe [gulp-consolidate](https://github.com/timrwood/gulp-consolidate) + [nunjucks](https://github.com/mozilla/nunjucks)? I haven't tried it myself yet, but I think you should be able to achieve a similar workflow with that combo.

**Comment by nenadjelovac** [comment]
@silvenon I think @maranomynet pretty much summed up all issues.

**Comment by at0g** [comment]
Could it be this line setting options/context in a closure above the call to each file?
https://github.com/carlosl/gulp-nunjucks-render/blob/master/index.js#L8

In the case of the OP, perhaps the nunjucks engine does not clone the data context, causing the original context to be updated (by reference) when `set` is called? As the data context is created in a closure well above each through stream, the values would persist and show on multiple renders.

eg.
**page1.htm** - sets `customAttr` to `class='foobar'`, which in turn sets `options.customAttr`

**page2.htm** - passed `options` as its context, where `options.customAttr` is already set to `class='foobar'`


I was working on [a fix](https://github.com/carlosl/gulp-nunjucks-render/pull/15) which is simply using _.extend(options, {}) to return a new data context for each file and can no longer replicate the OP issue.

**Comment by carlosl** [comment]
This is fixed with @at0g s updates. Updated NPM should work if you do an update. (> 0.2.0)
