### ISSUE TITLE
Default keyword arguments don't work on macros

### ISSUE THREAD

**Issue by revelt** [carlosl/gulp-nunjucks-render#60]
According to documentation [here](https://mozilla.github.io/nunjucks/templating.html#macro) and [here](https://mozilla.github.io/nunjucks/templating.html#keyword-arguments), you can set the defaults within macros:

    {% macro field(name, value='', type='text') %}

I discovered that default values don't work on `gulp-nunjucks-renderer`: when I set them, I get blank values. In the example snippet above, I'd be getting empty `value`, even if non-empty variable were being passed into it.

Can anybody confirm please, do you see this happening?

cheers

**Comment by TheDancingCode** [comment]
It works over here.

`value` is the second parameter, so make sure to pass it in the right order.
e.g.:
```js
{{ field('my name', 'my value', 'my type') }} 
```

**Comment by revelt** [comment]
@TheDancingCode aha! Thank you

**Comment by revelt** [comment]
It's funny no action for a year, it's not like maintainers didn't have time to address that, it's more of a time management and allocating certain amount of minutes per day and prioritising the issues... On other hand, the GitHub doesn't have any tools to help package maintainers - for example, out of all the libraries you have admin access, out of all their active issues, which ones are oldest? All that via single interface..
