### ISSUE TITLE
missing index.js in npm package of v2.1.0

### ISSUE THREAD

**Issue by changke** [carlosl/gulp-nunjucks-render#61]
Hi,

after an update to v2.1.0 there is no more "index.js", so require() is broken.

Please fix, thanks! :-)

**Comment by apranovich** [comment]
+1

**Comment by RZhosan** [comment]
+1

**Comment by daphnesmit** [comment]
+1

**Comment by JeroenReumkens** [comment]
+1

**Comment by RZhosan** [comment]
As a quick solution you can replace

"gulp-nunjucks-render": "https://github.com/carlosl/gulp-nunjucks-render"

in package.json

**Comment by revelt** [comment]
That's a good case example why [np](https://github.com/sindresorhus/np) should be used instead of `git push` + `npm publish` combo

**Comment by kristijanhusak** [comment]
Hey guys, my bad. I published 2.2.0. Please test it out and see if everything is ok.

**Comment by RZhosan** [comment]
@kristijanhusak No, 2.2.0 doesn't work for me

**Comment by revelt** [comment]
no luck, 2.2.0 has no index.js when installed under `npm i -D`:

![dev_install](https://cloud.githubusercontent.com/assets/8344688/24804729/60c2fd06-1ba7-11e7-8f73-8178957337cc.png)

**Comment by revelt** [comment]
related to #62

**Comment by kristijanhusak** [comment]
Move conversation to #62 .
