### ISSUE TITLE
Can't import v2.2.0

### ISSUE THREAD

**Issue by LeoIannacone** [carlosl/gulp-nunjucks-render#62]
Hi, I can't import latest version.

```
[15:40:24] Error: Cannot find module 'gulp-nunjucks-render' from 'my-home-project'
```

**Comment by jorupp** [comment]
It looks like the NPM package may be missing the index.js file?

**Comment by kristijanhusak** [comment]
Anyone know the reason why there is no index.js file on npm package? Everything looks ok here on the latest tag https://github.com/carlosl/gulp-nunjucks-render/tree/2.2.0

**Comment by revelt** [comment]
@kristijanhusak I don't see anything wrong anywhere, but there is a list of steps that for example np performs upon publishing. If this was happening to me, I'd remove node_modules, then install deps `npm i`, then run tests, if all still fine, publish via `np patch`.

I don't see .npmignore, but maybe there's one on yours, turn on show hidden files and double-check.

Maybe something's dodgy on the version control side? I'll try to git clone and have a look via SourceTree.

**Comment by revelt** [comment]
@kristijanhusak check out https://www.npmjs.com/package/np

**Comment by kristijanhusak** [comment]
Version 2.2.1 is out. I tried installing it, index.js properly exists.
@revelt thanks for the NP suggestion, it helped me out. I had too old version of npm, that's why issues occurred. Please test it out and see if everything is ok.
Apologies one more time.

**Comment by revelt** [comment]
My templates do render fine on `2.2.1`. There are differences now with Nunjucks v3, some of my content blocks are now empty but that's a different problem.

**Comment by revelt** [comment]
#54 can be closed then?

**Comment by kristijanhusak** [comment]
I closed it. Can we close this one too?
