### ISSUE TITLE
Missing the nl2br filter

### ISSUE THREAD

**Issue by zomars** [carlosl/gulp-nunjucks-render#63]
I'm getting this error when trying to use the [nl2br](https://mozilla.github.io/nunjucks/templating.html#nl2br) filter:

```
Error: filter not found: nl2br
```

**Comment by TheDancingCode** [comment]
The `nl2br` filter works just fine here. I'm guessing you're running an older version of this plugin. Your best bet is to reinstall gulp-nunjucks-render.
