### ISSUE TITLE
Add info to docs

### ISSUE THREAD

**Issue by molszanski** [carlosl/gulp-nunjucks-render#9]
Hey, 

in every nunjucks template you add a magic variable name that is filename the is being processed. 

I think you should add it to docs page

**Comment by at0g** [comment]
Won't this create a collision if the data context contains a `name` key?

eg.
**thing.nunj**
```
<label>Name: <input type="text" value="{{ name }}"></label>
```

**thing.html**
```
<label>Name: <input type="text" value="thing.nunj"></label>
```

Seems like `name` could be a fairly common key - can I suggest renaming it to something unlikely to cause a collision, such as `_name`, `_filename`, `$template_name` etc.
